services:
  postgres:
    image: postgres:15
    container_name: fraudlens-postgres
    environment:
      POSTGRES_DB: fraudlens
      POSTGRES_USER: fraudlens
      POSTGRES_PASSWORD: fraudlens
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fraudlens -d fraudlens"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: fraudlens-redis
    ports:
      - "6379:6379"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: fraudlens-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: fraudlens-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.15.1
    container_name: fraudlens-mlflow
    ports:
      - "5000:5000"
    command: mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri sqlite:///mlflow.db --default-artifact-root /mlruns
    volumes:
      - mlflow_data:/mlruns

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: fraudlens-api
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      DATABASE_URL: postgresql+psycopg2://fraudlens:fraudlens@postgres:5432/fraudlens
      REDIS_HOST: redis
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      MLFLOW_TRACKING_URI: http://mlflow:5000
    ports:
      - "8000:8000"
    volumes:
      - ./artifacts:/app/artifacts
      - ./reports:/app/reports

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dashboard
    container_name: fraudlens-dashboard
    depends_on:
      - api
    environment:
      DATABASE_URL: postgresql+psycopg2://fraudlens:fraudlens@postgres:5432/fraudlens
      REDIS_HOST: redis
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      MLFLOW_TRACKING_URI: http://mlflow:5000
    ports:
      - "8501:8501"
    volumes:
      - ./artifacts:/app/artifacts
      - ./reports:/app/reports


  streaming:
    build:
      context: .
      dockerfile: Dockerfile.streaming
    container_name: fraudlens-streaming
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_started
    environment:
      DATABASE_URL: postgresql+psycopg2://fraudlens:fraudlens@postgres:5432/fraudlens
      REDIS_HOST: redis
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      MLFLOW_TRACKING_URI: http://mlflow:5000
    volumes:
      - ./artifacts:/app/artifacts
      - ./reports:/app/reports

volumes:
  postgres_data:
  mlflow_data:
