from __future__ import annotations

import json
from typing import Any, Optional
from sqlalchemy import create_engine, text
from sqlalchemy.engine import Engine
from src.config.settings import settings

VALID_ALERT_STATUSES = {"OPEN", "UNDER_REVIEW", "CONFIRMED_FRAUD", "FALSE_POSITIVE", "CLOSED"}


def get_engine() -> Engine:
    return create_engine(settings.database_url, pool_pre_ping=True, future=True)


def init_db(engine: Optional[Engine] = None) -> None:
    engine = engine or get_engine()
    schema_path = "sql/create_tables.sql"
    with open(schema_path, "r", encoding="utf-8") as f:
        sql = f.read()
    with engine.begin() as conn:
        for statement in sql.split(";"):
            if statement.strip():
                conn.execute(text(statement))


def insert_transaction(txn: dict[str, Any], engine: Optional[Engine] = None) -> None:
    engine = engine or get_engine()
    with engine.begin() as conn:
        conn.execute(text("""
            INSERT INTO transactions
            (transaction_id, customer_id, amount, merchant_category, merchant_country, device_type, card_present, transaction_time)
            VALUES (:transaction_id, :customer_id, :amount, :merchant_category, :merchant_country, :device_type, :card_present, COALESCE(:transaction_time, CURRENT_TIMESTAMP))
            ON CONFLICT (transaction_id) DO NOTHING
        """), {
            "transaction_id": txn.get("transaction_id"),
            "customer_id": txn.get("customer_id"),
            "amount": txn.get("amount"),
            "merchant_category": txn.get("merchant_category", "unknown"),
            "merchant_country": txn.get("merchant_country", "US"),
            "device_type": txn.get("device_type", "unknown"),
            "card_present": not bool(txn.get("is_card_not_present", 0)),
            "transaction_time": txn.get("transaction_time"),
        })


def insert_prediction(record: dict[str, Any], engine: Optional[Engine] = None) -> int | None:
    engine = engine or get_engine()
    payload = dict(record)
    if isinstance(payload.get("shap_explanation"), (dict, list)):
        payload["shap_explanation"] = json.dumps(payload["shap_explanation"])
    with engine.begin() as conn:
        result = conn.execute(text("""
            INSERT INTO fraud_predictions
            (transaction_id, model_version, fraud_probability, rule_score, final_risk_score, prediction_label, shap_explanation)
            VALUES (:transaction_id, :model_version, :fraud_probability, :rule_score, :final_risk_score, :prediction_label, :shap_explanation)
            RETURNING prediction_id
        """), payload)
        return result.scalar_one_or_none()


def create_alert_if_needed(score: dict[str, Any], engine: Optional[Engine] = None) -> int | None:
    engine = engine or get_engine()
    if score.get("risk_level") not in {"MEDIUM", "HIGH"} and int(score.get("prediction_label", 0)) != 1:
        return None
    with engine.begin() as conn:
        result = conn.execute(text("""
            INSERT INTO fraud_alerts (transaction_id, risk_level, alert_status, investigation_notes)
            VALUES (:transaction_id, :risk_level, 'OPEN', :notes)
            RETURNING alert_id
        """), {
            "transaction_id": score.get("transaction_id"),
            "risk_level": score.get("risk_level"),
            "notes": "Auto-generated by FraudLens scoring engine.",
        })
        return result.scalar_one()


def list_alerts(status: str | None = None, limit: int = 100, engine: Optional[Engine] = None) -> list[dict[str, Any]]:
    engine = engine or get_engine()
    query = """
        SELECT a.alert_id, a.transaction_id, a.risk_level, a.alert_status, a.assigned_to,
               a.investigation_notes, a.created_at, a.updated_at,
               p.fraud_probability, p.rule_score, p.final_risk_score, p.shap_explanation
        FROM fraud_alerts a
        LEFT JOIN LATERAL (
            SELECT * FROM fraud_predictions p
            WHERE p.transaction_id = a.transaction_id
            ORDER BY p.scored_at DESC
            LIMIT 1
        ) p ON true
    """
    params: dict[str, Any] = {"limit": limit}
    if status:
        query += " WHERE a.alert_status = :status"
        params["status"] = status
    query += " ORDER BY a.created_at DESC LIMIT :limit"
    with engine.begin() as conn:
        rows = conn.execute(text(query), params).mappings().all()
    return [dict(row) for row in rows]


def get_alert(alert_id: int, engine: Optional[Engine] = None) -> dict[str, Any] | None:
    engine = engine or get_engine()
    with engine.begin() as conn:
        row = conn.execute(text("""
            SELECT * FROM fraud_alerts WHERE alert_id = :alert_id
        """), {"alert_id": alert_id}).mappings().first()
    return dict(row) if row else None


def update_alert_status(alert_id: int, new_status: str, changed_by: str = "system", notes: str | None = None, engine: Optional[Engine] = None) -> dict[str, Any]:
    if new_status not in VALID_ALERT_STATUSES:
        raise ValueError(f"Invalid status {new_status}. Valid statuses: {sorted(VALID_ALERT_STATUSES)}")
    engine = engine or get_engine()
    with engine.begin() as conn:
        existing = conn.execute(text("SELECT alert_status FROM fraud_alerts WHERE alert_id = :alert_id"), {"alert_id": alert_id}).mappings().first()
        if not existing:
            raise LookupError(f"Alert {alert_id} not found")
        old_status = existing["alert_status"]
        conn.execute(text("""
            UPDATE fraud_alerts
            SET alert_status = :new_status,
                investigation_notes = COALESCE(:notes, investigation_notes),
                updated_at = CURRENT_TIMESTAMP
            WHERE alert_id = :alert_id
        """), {"alert_id": alert_id, "new_status": new_status, "notes": notes})
        conn.execute(text("""
            INSERT INTO alert_status_history (alert_id, old_status, new_status, changed_by)
            VALUES (:alert_id, :old_status, :new_status, :changed_by)
        """), {"alert_id": alert_id, "old_status": old_status, "new_status": new_status, "changed_by": changed_by})
    updated = get_alert(alert_id, engine)
    assert updated is not None
    return updated


def persist_scored_transaction(txn: dict[str, Any], score: dict[str, Any], engine: Optional[Engine] = None) -> int | None:
    """Persist transaction, prediction, and optional alert in one high-level call."""
    engine = engine or get_engine()
    insert_transaction(txn, engine)
    insert_prediction(score, engine)
    return create_alert_if_needed(score, engine)
